### ISSUE TITLE
Erreur lors de l'installation de l'extenssion

### ISSUE THREAD

**Issue by JulesMichael** [Qowala/browser-extension#21]
Salut!

J'ai deja téléchargé et installé plusieurs fois l'extension afin d'avoir la dernière version de l'extension. Malheureusement, lorsque j'installe l'extension (sur Google Chrome), l'erreur suivante revient toujours:

```
L'installation de cette extension a généré des avertissements :
Unrecognized manifest key 'applications'.
```

Même si cette erreur n'a pas l'air de nuire au bon fonctionnement de l'extension, je la trouve un tant soit peu dérangeante .

**Comment by KillianKemps** [comment]
Salut !

Ce que tu décris est une erreur "normale". C'est parce que pour être sur le Firefox Add-ons Marketplace, nous avons ajouté un identifiant dans le manifest.json qui n'est pas reconnu par Google Chrome.
Chrome affiche donc une erreur, mais ce n'est pas grave car elle n'est pas bloquante.

**Comment by JulesMichael** [comment]
Humm d'accord ^^ Je vais devoir apprendre à vivre avec alors haha.
