### ISSUE TITLE
Display dashboard with my last week consumption

### ISSUE THREAD

**Issue by KillianKemps** [Qowala/browser-extension#24]
Add a chart displaying time spent last week on each website.

**Comment by elegaanz** [comment]
Something like that, or are you thinking of a diffrent kind of chart?

![capture d ecran du 2017-06-04 13 58 21](https://cloud.githubusercontent.com/assets/16254623/26761775/fc438d96-492d-11e7-983e-277b60aeedf6.png)

**Comment by KillianKemps** [comment]
Yes something like that would be nice. I'm just not sure yet how to handle user's custom websites.
In the mockups you see, the popular websites have each their logo on which the user can select in order to display on the chart.
But, if the user adds customs websites, how could we display it?
Should we save the websites' favicons when we visit them? Should we display text for custom URLs?

I think for a first version, we should just do a basic dashboard with only popular social networks.
