### ISSUE TITLE
Pre-compile templates with Webpack

### ISSUE THREAD

**Issue by KillianKemps** [Qowala/browser-extension#25]
After having submitted the v0.3.0 of the plugin to validation at Firefox AMO, the review has rejected the plugin for the following reason:

```
This version did not pass the review because of the following issues:

1) The use of 'unsafe-eval' is not allowed in the manifest.json's CSP as it can cause major security issues.
```

We have to find a solution to remove this CSP rule

**Comment by KillianKemps** [comment]
According to the error I see when loading the plugin without the CSP:
```
[Vue warn]: It seems you are using the standalone build of Vue.js in an environment with Content Security Policy that prohibits unsafe-eval. The template compiler cannot work in this environment. Consider relaxing the policy to allow unsafe-eval or pre-compiling your templates into render functions.
```

I think, we have no other choice than to pre-compile our templates. What do you think @Bat41 ?

**Comment by elegaanz** [comment]
Yes, we should pre-compile the templates. I think Webpack is a good solution to achieve that.
