### ISSUE TITLE
Dashboard de l'activité

### ISSUE THREAD

**Issue by JulesMichael** [Qowala/browser-extension#27]
Salut,
Je viens pour proposer une feature pour l'extension Qowala.
En effet, je trouverais intéressant la possibilité d'accéder à un dashboard récapitulatif de notre activité. Par exemple pour connaitre le temps passé sur twitter pendant la semaine.

**Comment by KillianKemps** [comment]
Salut JulesMichael,

C'est une bonne idée, nous avons déjà commencé à travailler sur les maquettes pour ça.
Je t'invite à regarder cette issue https://github.com/Qowala/browser-extension/issues/24 qui a déjà été ouverte.

Si c'est bien la même idée que ce que tu décris ici, je vais fermer cette issue. ;)

**Comment by JulesMichael** [comment]
Quel couillon je suis... Je n'ai meme pas pris le temps de regarder la seul issue qu'il y avait 🤦

**Comment by KillianKemps** [comment]
Pas de soucis haha
