### ISSUE TITLE
Custom domains

### ISSUE THREAD

**Issue by elegaanz** [Qowala/browser-extension#5]
We should have an option to add our own domains.

**Comment by KillianKemps** [comment]
Good idea!

We were already working on it. If you wish to contribute, we have a first draft of a screen to allow to add your own domain. Even if the design is not yet finished, the JS and HTML parts should not change much in the next mockups.

As you can see below, we designed a new page allowing the user to add domains to be tracked. This page should be accessible through the Settings button in the module manager of the browser.

What is needed to be done is: 
1. Create page which opens when the user access the Settings of the module from the Module Manager
2. Add the form which adds domains to [this list](https://github.com/Qowala/browser-extension/blob/master/configuration.json)
3. Add the CSS and the logo to the page.

It may be some work, so please let me know what you would like to do and I will take charge of the rest.

![controler contenus sites version b](https://cloud.githubusercontent.com/assets/6884630/26037029/ffd09ce0-38ea-11e7-8bcc-45e4ade05ba5.png)
Comments about the mockup:
 - It is written "block" on the mockup, but you can replace it by "track" as for the moment we only track the time spent on these websites
 - You only need to integrate the left column called "Settings"
 - You can also add Qowala's logo at the top if you wish, I just have to give you the image

Thanks for your help!

**Comment by elegaanz** [comment]
I started working on it. Could you send me the logo please ? :slightly_smiling_face:

**Comment by KillianKemps** [comment]
Great thank you!

Here is the logo, but you may need to resize it to make it smaller. Is it okay for you?

![logo-icn name-green](https://cloud.githubusercontent.com/assets/6884630/26057225/0af802aa-3979-11e7-8e2a-04d0ae8ba941.png)
